publish_to: https://pub.dev

name: spidart
version: 1.0.0

description: A fast and simple-to-use web crawler written in Dart.

homepage: https://github.com/vxern/spidart
repository: https://github.com/vxern/spidart
issue_tracker: https://github.com/vxern/spidart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  web_scraper: ^0.1.4

dev_dependencies:
  test: ^1.14.4
  words: ^0.0.2+1
