name: spidart
description: A fast and simple-to-use web crawler written in Dart
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  
dependencies: 
  web_scraper: ^0.1.4
